!classDefinition: #Pepe category: 'Ejercicio1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: 'Ejercicio1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'as yet unclassified' stamp: 'MP 8/19/2021 20:44:46'!
caminar: unaCantidadDeKm
	^unaCantidadDeKm! !

!Pepe class methodsFor: 'as yet unclassified' stamp: 'MP 8/19/2021 20:32:31'!
hola
	"Pepe debe responder chau"

	^'chau'.! !
